permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: 李科男
  email: f8cncn@gmail.com
  link: http://westeast.github.io
  github: http://github.com/westeat

# 站点信息
title: 李科男的博客
description: 李科男的博客
url: http://westeast.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: https://avatars0.githubusercontent.com/u/2304604?v=3&s=460
favicon: http://www.nuomi.com/favicon.ico

# google analytics 设置
ga:
  id: UA-54767140-1
  url: westeast.github.io

# disqus 设置
disqus:
  shortname: westeast-zh

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Python
  - OpenStack

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
